### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by stenio123** [AlexSergey/rocket#1]
Thank you for the great project!

Just two comments regarding installation:

1) I got an error when doing 'npm install' on the server folder, fixed by adding a 'version' parameter on server/package.json

2) I got an error on the server npm install, when going through kerberos. Searching online, this seems a recurring issue for Ubuntu-based systems. It was solved by installing "sudo apt-get install libkrb5-dev"

Thanks!

**Comment by AlexSergey** [comment]
Sorry for late answer. I added version field into server package json.
