### ISSUE TITLE
Unknown task jsLibs 

### ISSUE THREAD

**Issue by rpolonsky** [AlexSergey/rocket#2]
В тасках для gulp есть watch.js, там описан таск htmlWatch, который внутри себя вызывает таск jsLibs, этот таск нигде не описан.

Как с вами можно связаться? Решили использовать ваш бойлеплейт и хотелось бы узнать описание jsLibs как можно раньше.

Мой email rvpolonskiy@gmail.com

**Comment by AlexSergey** [comment]
Hi! This is my bug. All libraries included in JSX files using browserify. jsLibs - this old, unused task. I am deleting it now.
